### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by Cyjanss** [Lolincolc/gmusic_wrapped#1]
![2018-12-25_12-52-46](https://user-images.githubusercontent.com/22357175/50421868-1125d080-0844-11e9-945c-1bf22c40f32c.jpg)

Hello, there is an error from the line "json.load(file)", do you kown why ? 

Thanks,

**Comment by nanodan52** [comment]
When using Python3, I get this error too:

Traceback (most recent call last):
  File "main.py", line 214, in <module>
    main()
  File "main.py", line 200, in main
    parse_json(file, cursor)
  File "main.py", line 47, in parse_json
    json_object = json.load(file)
  File "D:\Programs (x64)\Dev Tools\Python 3\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "D:\Programs (x64)\Dev Tools\Python 3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2117168: character maps to <undefined>

------------
When using Python2, no such error, but it completes instantly and the output is empty.

**Comment by Cyjanss** [comment]
Yes, so it's the same error... strange...

**Comment by nanodan52** [comment]
The newest main.py from commit 49193ee0d078953b90d674fefb47f4d7bf4c4c11
instead yields the following decoding error:
-------------
Traceback (most recent call last):
  File "main.py", line 231, in <module>
    main()
  File "main.py", line 217, in main
    parse_json(file, cursor)
  File "main.py", line 64, in parse_json
    json_object = json.load(file)
  File "D:\Programs (x64)\Dev Tools\Python 3\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "D:\Programs (x64)\Dev Tools\Python 3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2117168: character maps to <undefined>

------------
which is largely the same error but at different positions. 
This comment is probably redundant, but I figured I'd share it anyway.

**Comment by Lolincolc** [comment]
Yes this script is designed to be used with python 2.7 that could explain error your are facing... Could you try running it with Python 2.7 and tell me if it works ?

**Comment by brettgoss** [comment]
@Lolincolc I added python3 support in my fork, but I also have a number of other changes including a autopep8 formatting change, so I'm hesitant to open a PR. Is there a preferred formatting or style guide that you're using? I'd be happy to contribute if you'd like!

**Comment by Lolincolc** [comment]
@brettgoss awesome! I checked your fork, it looks great. Feel free to open a PR, I'd be happy to integrate your changes!

**Comment by brettgoss** [comment]
@Lolincolc Thanks! I cleaned up my commits a bit and opened a PR.

**Comment by Kiina** [comment]
I tried your python 3 fork:

`UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 929: character maps to <undefined>`

Running the same fork on python 2:

```
main.py:28: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if (fr == "A ├⌐cout├⌐"):
main.py:38: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if (fr == "A ├⌐cout├⌐"):
Traceback (most recent call last):
  File "main.py", line 237, in <module>
    main()
  File "main.py", line 234, in main
    gen_report(cursor, data, expect)
  File "main.py", line 188, in gen_report
    print('{0} - {1}'.format(row[0], row[1]))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
```

The original project seems to work under python2.

**Comment by brettgoss** [comment]
@Kiina Looks like it's still trying to open the file in ascii rather than utf-8. I'm not getting the same error on my fork though, do you have more information about how to reproduce that error?

**Comment by Kiina** [comment]
> @Kiina Looks like it's still trying to open the file in ascii rather than utf-8. I'm not getting the same error on my fork though, do you have more information about how to reproduce that error?


Try this as your MyActivity.json:

```
[{
  "header": "Google Play Music",
  "title": "Listened to 말 조 심 (Watch Your Mouth)",
  "description": "Dok2(도끼)",
  "time": "2018-12-05T19:02:07.400Z",
  "products": ["Google Play Music"]
}]
```

I think the issue is with the utf-8 in the description. Removing it makes it run through.

**Comment by brettgoss** [comment]
@Kiina Interesting, using that json is also working for me on my fork using Python 3.7.0. If you're on an older version of Python, are you able to try upgrading and see if that resolves the issue? I'm not too sure what else would be causing that error, as Python should allow unicode.

**Comment by Kiina** [comment]
Well I'm on latest python, so that shouldn't be an issue. I expected it to be some error with the code as it works with it just being in the title, but as soon as it's in the description it crashed. But if it works for you it seems like the problem is another one.
