### ISSUE TITLE
Google Play Music Data is no longer a json

### ISSUE THREAD

**Issue by broseidon91** [Lolincolc/gmusic_wrapped#4]
Hey, found this project. Just wanted to let you know that downloading your data from google now gives you a zip containing CSV data of your tracks and playlists. Anyone looking to use this in 2019 will be unable to generate a file.

**Comment by matthewnlee** [comment]
FYI - JSON format is still available. You have to scroll past Google Play Music in Takeout and continue to My Activity!

**Comment by broseidon91** [comment]
Ahh okay, my bad. The help page was in french so I wasn't sure you were selecting a different thing

**Comment by broseidon91** [comment]
@matthewnlee Also just so you know, your website image header when shared on facebook still says 2018 :)

**Comment by matthewnlee** [comment]
Unfortunately I've practically forgotten how to get Python set up, so I'm not even able to generate an image :|

**Comment by broseidon91** [comment]
Fair enough, its no big deal lol

**Comment by matthewnlee** [comment]
Got it to work - is the font weird on your image? (like Times)
![Screen Shot 2019-12-05 at 3 26 44 PM](https://user-images.githubusercontent.com/24398709/70271053-a9764600-1773-11ea-9b8b-2094f2599253.png)

Also it's displaying my 2018 results!

**Comment by broseidon91** [comment]
Im not sure, i ended up using the website instead
